In [1]:
import torch
from torch import nn

# Hard Coded Paramter and Weights

In [2]:
X = torch.tensor([
    [10.0],
    [38.0],
    [100.0],
    [150.0]
])

model = nn.Linear(1, 1)

In [3]:
model.bias, model.weight

(Parameter containing:
 tensor([-0.8904], requires_grad=True),
 Parameter containing:
 tensor([[-0.7835]], requires_grad=True))

In [4]:
model.bias = nn.Parameter(torch.tensor([32.0]))
model.weight = nn.Parameter(torch.tensor([[1.8]]))

In [5]:
model.bias, model.weight

(Parameter containing:
 tensor([32.], requires_grad=True),
 Parameter containing:
 tensor([[1.8000]], requires_grad=True))

In [6]:
y_predict = model(X.float())
y_predict

tensor([[ 50.0000],
        [100.4000],
        [212.0000],
        [302.0000]], grad_fn=<AddmmBackward0>)

# Learning The Parameters

In [7]:
X = torch.tensor([[38.0], [12.6]], dtype=torch.float32)
y = torch.tensor([[100.4], [54.68]], dtype=torch.float32)

model = nn.Linear(1, 1)
loss_function = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

for i in range(10000):
    optimizer.zero_grad()
    output = model(X)
    loss = loss_function(output, y)
    loss.backward()
    optimizer.step()

    if i % 100 == 0:
        print(i, loss.item(), model.weight.item(), model.bias.item())


0 5712.2119140625 4.388186454772949 0.21405988931655884
100 188.37258911132812 2.7656965255737305 1.4191410541534424
200 173.81300354003906 2.727625846862793 2.6247293949127197
300 160.37867736816406 2.6910560131073 3.7827889919281006
400 147.98269653320312 2.655927896499634 4.895195007324219
500 136.54489135742188 2.6221847534179688 5.963743686676025
600 125.99110412597656 2.5897724628448486 6.990167617797852
700 116.25300598144531 2.5586371421813965 7.976128101348877
800 107.26771545410156 2.528729200363159 8.923213958740234
900 98.97679901123047 2.5000009536743164 9.832968711853027
1000 91.32672119140625 2.472404718399048 10.706859588623047
1100 84.26793670654297 2.4458963871002197 11.546296119689941
1200 77.75475311279297 2.4204330444335938 12.352642059326172
1300 71.7448501586914 2.3959741592407227 13.12720012664795
1400 66.1995620727539 2.372479200363159 13.871223449707031
1500 61.08293151855469 2.349910259246826 14.585909843444824
1600 56.36175537109375 2.3282315731048584 15.272

In [10]:
test_data = torch.tensor([[50.0]])

result = model(test_data)
result

tensor([[122.3303]], grad_fn=<AddmmBackward0>)